addons:
  code_climate:
    repo_token:
      secure: qi61gL97bZiLMLsNOManrsMmy2b5JwvZml/Fu77DsMRvxKeqAFwWIbz4iNxOw2tg1PsIWLZbKrPcOftinUf0uXt9IjyWxw9qZuEBG6+VTm7e+PQsDCAtv/xufahC5Sq6j4t+gXoFEu2OIdWags1/4WSLwBvMiRT0SEpxpvw+CDTM/lysFytmHz3nSIR3tMNmkZiKvxXaBa1nZNuOATwA5x2Cezj4T8myjaarlcUEZZPEnVKzwiLv+NwCnQmFamNIHrLHvB0PiYMFPhTzkXopmseuc+gqfCQ/plX1aK5qfS4WDpbqZ9T4yx/GFFXq6lYtQ8bzUZESYb6gmTHQEbO4AqD7rNZDfh1ZrbDhOTW7VvCpUx3w/i3yhGprBJWw7UM0ez/HI/TSdPtAhJt1B0Wgb/8sq2JEWNKaJ4gqG+4N0dnSrsNoSS0KGGVTeSSaGCrxbkTJDLPayIoWajfqp3pFtkvdeot652qtSwm+/C94NoDK16LRY7NCQr+xCfIukVjtHDsO5DSXVmdTOml2kJkyHXDLM4Qg1SN7zXT/Z3GEcUyfaXju9SW7sNNMpsOCrdnHBdKfq2zrvo1wAub+ERWpvIqKmDYuOFFvleuUzj8QEjL4Fv63SxKX+JR8a2pCN2gbit77VXJ02mLJrNtqCcqy6p/3effGVYEJfEcBkUD5Rog=
language: node_js
node_js:
- node
before_script:
- npm install codeclimate-test-reporter -g
script:
- make lint
- make test-coverage
after_script:
- codeclimate-test-reporter <./coverage/lcov.info
env:
  global:
    secure: elW4LXm9sTkG5A0dZ7ZQfZVhsFbHCy47IuULhDoQtFbVgp8GnJ4iWMGp5SaY8JblQPb4FhBOT/D/zsbbIOSCloI4Yxxoct0r5DNH57KPFdUmYhvnepwD+dTcIorK6Gou4mem+XFxXpATInd3NaDr1M6HWQYCfU3ZgmC8EiqFcU0klKSvGT+Gr6H0UQ6veTPrpXbvwXWPXfUXDEQf7Mtqn9WSoEYdKa80h6pbyDrLLru74xhTPNumaxOWzuteATsx1ND2rYdLANlwQ1+2qnOcAbD/ZBb2iWncdsk+mQS2DeD6/xhULRFm5I65qz+6Z6EGdeipGopoqucG/sZifiBBE1+7eud4oTLkjcsRw61O1VfShRgOw4TqHfvHzEDDEdxw4bC67Q5gP/0mQrKQ5001sC1dDOIZ0vH5pWOaEhrPYrnjwKDKY6UTf4y7i8lYLBzrQfC40g7UYH6A/Ewg63LXZ10JHr0GbQSb+KcJ28YJpSbSM31GZyemxkpXAoaIz6X67f0Lhzq8cUdcuZZR+SfcPtE/xvps9ZhOA8w4Pj6jgf2B0HP8yz+rZ5VKkq9Mnond12+m6eJKyqBek/tSbCXLu81RfIcF40RdhpjfESuLVAwpm4XM2AkvmnZkqGUiTcZ+y9GJWiqI6p2RXf8ksSmDP25nM9hNtDTfw9gfOWhQlK8=
