language: node_js

node_js:
  - node

addons:
  code_climate:
    repo_token: a68611c5c731fb8213f65c1b19fd8bf6adbc0f7bbaed746b994dc8a49bff0be0

before_script:
  - npm install codeclimate-test-reporter -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

script:
  - make lint
  - make test
