addons:
  code_climate:
    repo_token:
      secure: XYYOlm3napFy/TkV/tdIcmQG4fXeZ/wOOTMEjROTzyL1bQ3C0XVSsKytFPoyoA69Qsx7WaR5SmyPp5ISd3dTAmrFmDmPCf7i6dhngGyZ0cAd5W+zvL+vYsozx5HVMnHImE2ZZFU/l/EDMDb6qGyHPzZhuiQmaNcv1uIZlt8GcXwvgIwK4898XEC5CTWyokcJVFx8YdIXruVMF0ivIVAquxeltyHY9w4CmyjYfQxzI2oaTOxgEAXiZw0yFEgiOn90juIL4dpe2fnHMGMUFjfQKKfve8d9Znv5Zy8LmEAalE6q1jOiP0zmvPTTkbhNik4ZToKIyuqzNFGzZ6s9mjYZ529ym777v99FQkgPFrwajWDhciQ8xAdR92OptpNYYWSeF8JB6x/Ui8/rHG3l5BO6SXdPiT/gbT15SFih2P1Gv1ai04bYTFlNdRUZX4p1hdqEB3uiz2rv/DIiaP2+0rImb/OQQigaJEYMcIcKrL5vyhACx0Nwf3r5+GSaexsyYmUjHqKocDznJZFoPRiSE3JaicAAVXdo7JTorpxSTOeNlbfWKp0te1S3qoCQ17EB3f1oEfT4T0FzZw42x/sIS9ngIH4OQ1eWyoS6wORE/fcD1MudXtciU8jlTGd6uv0/j90EMXwB1Au53+cklxEPye8Jjf0TfwPyZ/6LlEcgwmsibNk=

language: node_js
node_js:
  - node
before_script:
  - npm install codeclimate-test-reporter -g

script:
  - make lint
  - make test-coverage

after_script:
  - codeclimate-test-reporter <./coverage/lcov.info
