addons:
  code_climate:
    repo_token:
      secure: qi61gL97bZiLMLsNOManrsMmy2b5JwvZml/Fu77DsMRvxKeqAFwWIbz4iNxOw2tg1PsIWLZbKrPcOftinUf0uXt9IjyWxw9qZuEBG6+VTm7e+PQsDCAtv/xufahC5Sq6j4t+gXoFEu2OIdWags1/4WSLwBvMiRT0SEpxpvw+CDTM/lysFytmHz3nSIR3tMNmkZiKvxXaBa1nZNuOATwA5x2Cezj4T8myjaarlcUEZZPEnVKzwiLv+NwCnQmFamNIHrLHvB0PiYMFPhTzkXopmseuc+gqfCQ/plX1aK5qfS4WDpbqZ9T4yx/GFFXq6lYtQ8bzUZESYb6gmTHQEbO4AqD7rNZDfh1ZrbDhOTW7VvCpUx3w/i3yhGprBJWw7UM0ez/HI/TSdPtAhJt1B0Wgb/8sq2JEWNKaJ4gqG+4N0dnSrsNoSS0KGGVTeSSaGCrxbkTJDLPayIoWajfqp3pFtkvdeot652qtSwm+/C94NoDK16LRY7NCQr+xCfIukVjtHDsO5DSXVmdTOml2kJkyHXDLM4Qg1SN7zXT/Z3GEcUyfaXju9SW7sNNMpsOCrdnHBdKfq2zrvo1wAub+ERWpvIqKmDYuOFFvleuUzj8QEjL4Fv63SxKX+JR8a2pCN2gbit77VXJ02mLJrNtqCcqy6p/3effGVYEJfEcBkUD5Rog=

language: node_js

node_js:
- node

before_script:
- npm install codeclimate-test-reporter -g

script:
- make lint
- make test-coverage

after_script:
- codeclimate-test-reporter <./coverage/lcov.info
